<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'id',
'ndays',
'cweekend',
'choliday',
'cday1',
'cday2',
'cunavailable',
'cunavailabletext',
'tooltipfields',
'adddays',
'intName',
'intValue',
'weekends',
'minTime',
'maxTime',
'clickEvent',
'showTitle' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'id' => array( 'import_field' ),
'ndays' => array( 'import_field1' ),
'cweekend' => array( 'import_field2' ),
'choliday' => array( 'import_field3' ),
'cday1' => array( 'import_field4' ),
'cday2' => array( 'import_field5' ),
'cunavailable' => array( 'import_field6' ),
'cunavailabletext' => array( 'import_field7' ),
'tooltipfields' => array( 'import_field8' ),
'adddays' => array( 'import_field9' ),
'intName' => array( 'import_field10' ),
'intValue' => array( 'import_field11' ),
'weekends' => array( 'import_field12' ),
'minTime' => array( 'import_field13' ),
'maxTime' => array( 'import_field14' ),
'clickEvent' => array( 'import_field15' ),
'showTitle' => array( 'import_field16' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16' ) ),
'cellMaps' => array(  ) ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'id',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'ndays',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'cweekend',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'choliday',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'cday1',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'cday2',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'cunavailable',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'cunavailabletext',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'tooltipfields',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'adddays',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'intName',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'intValue',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'weekends',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'minTime',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'maxTime',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'clickEvent',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'showTitle',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 13,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>