<?php
			$optionsArray = array( 'totals' => array( 'id' => array( 'totalsType' => '' ),
'ndays' => array( 'totalsType' => '' ),
'cweekend' => array( 'totalsType' => '' ),
'choliday' => array( 'totalsType' => '' ),
'cday1' => array( 'totalsType' => '' ),
'cday2' => array( 'totalsType' => '' ),
'cunavailable' => array( 'totalsType' => '' ),
'cunavailabletext' => array( 'totalsType' => '' ),
'tooltipfields' => array( 'totalsType' => '' ),
'adddays' => array( 'totalsType' => '' ),
'intName' => array( 'totalsType' => '' ),
'intValue' => array( 'totalsType' => '' ),
'weekends' => array( 'totalsType' => '' ),
'minTime' => array( 'totalsType' => '' ),
'maxTime' => array( 'totalsType' => '' ),
'clickEvent' => array( 'totalsType' => '' ),
'showTitle' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'id',
'ndays',
'cweekend',
'choliday',
'cday1',
'cday2',
'cunavailable',
'cunavailabletext',
'tooltipfields',
'adddays',
'intName',
'intValue',
'weekends',
'minTime',
'maxTime',
'clickEvent',
'showTitle' ),
'exportFields' => array( 'id',
'ndays',
'cweekend',
'choliday',
'cday1',
'cday2',
'cunavailable',
'cunavailabletext',
'tooltipfields',
'adddays',
'intName',
'intValue',
'weekends',
'minTime',
'maxTime',
'clickEvent',
'showTitle' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'id' => array( 'export_field' ),
'ndays' => array( 'export_field1' ),
'cweekend' => array( 'export_field2' ),
'choliday' => array( 'export_field3' ),
'cday1' => array( 'export_field4' ),
'cday2' => array( 'export_field5' ),
'cunavailable' => array( 'export_field6' ),
'cunavailabletext' => array( 'export_field7' ),
'tooltipfields' => array( 'export_field8' ),
'adddays' => array( 'export_field9' ),
'intName' => array( 'export_field10' ),
'intValue' => array( 'export_field11' ),
'weekends' => array( 'export_field12' ),
'minTime' => array( 'export_field13' ),
'maxTime' => array( 'export_field14' ),
'clickEvent' => array( 'export_field15' ),
'showTitle' => array( 'export_field16' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16' ) ),
'cellMaps' => array(  ) ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'id',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'ndays',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'cweekend',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'choliday',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'cday1',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'cday2',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'cunavailable',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'cunavailabletext',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'tooltipfields',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'adddays',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'intName',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'intValue',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'weekends',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'minTime',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'maxTime',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'clickEvent',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'showTitle',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 13,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>